#!/bin/bash

# This is a thin wrapper around oro-cli that strips the Windows-style EOLs
# from the output if present. It is necessary when using oro-cli.exe on
# Linux since shells will interpret the line-endings as part of the result.

CURDIR=$(cd $(dirname "$0"); pwd)
# Get BUILDDIR and REAL_OROD

# Grab the value of $REAL_OROCLI which may be oro-cli.exe.
. "${CURDIR}/tests-config.sh"

"${REAL_OROCLI}" "$@" | sed 's/\r//'
